"""change table SchoolAdmin name to Admin

Revision ID: 00537726dcfb
Revises: 328eb4c57098
Create Date: 2019-01-24 13:13:23.839460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00537726dcfb'
down_revision = '328eb4c57098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('school_email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_school_email'), 'admin', ['school_email'], unique=True)
    op.drop_index('ix_scholl_admin_school_email', table_name='scholl_admin')
    op.drop_table('scholl_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scholl_admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('school_email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_scholl_admin_school_email', 'scholl_admin', ['school_email'], unique=True)
    op.drop_index(op.f('ix_admin_school_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
