"""add column school_id to table parent

Revision ID: 296af6463a50
Revises: 7a0be96e1555
Create Date: 2019-01-27 21:40:45.711819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296af6463a50'
down_revision = '7a0be96e1555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parent', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='foreignkey')
    op.drop_column('parent', 'school_id')
    # ### end Alembic commands ###
