"""add column email and password to parent table

Revision ID: 3797a2105abc
Revises: a73e33a5508c
Create Date: 2019-01-24 00:24:08.203979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3797a2105abc'
down_revision = 'a73e33a5508c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('parent', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_parent_email'), 'parent', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_email'), table_name='parent')
    op.drop_column('parent', 'password_hash')
    op.drop_column('parent', 'email')
    # ### end Alembic commands ###
