"""change column foreign key position from student_id on table User to school_id on table Student

Revision ID: 3c195d53fb91
Revises: dd4adf2842e8
Create Date: 2019-01-25 20:14:31.422658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c195d53fb91'
down_revision = 'dd4adf2842e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'user', ['school_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'student', ['student_id'], ['id'])
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'school_id')
    # ### end Alembic commands ###
