"""change foreignkey bill location from table Bill to table Student and add colum bill.relationship

Revision ID: 4014863e296b
Revises: 296af6463a50
Create Date: 2019-01-27 22:26:51.906039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4014863e296b'
down_revision = '296af6463a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bill_ibfk_1', 'bill', type_='foreignkey')
    op.drop_column('bill', 'student_id')
    op.add_column('student', sa.Column('bill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'bill', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'bill_id')
    op.add_column('bill', sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('bill_ibfk_1', 'bill', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
