"""add column active to table Parent

Revision ID: 65b63e0ecca6
Revises: 3c195d53fb91
Create Date: 2019-01-26 00:02:08.223540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b63e0ecca6'
down_revision = '3c195d53fb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'active')
    # ### end Alembic commands ###
