"""add table school

Revision ID: 7a0be96e1555
Revises: c53abdcc053d
Create Date: 2019-01-27 19:07:54.969448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a0be96e1555'
down_revision = 'c53abdcc053d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('school_id', sa.Integer(), nullable=True))
    op.drop_constraint('student_ibfk_1', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'school', ['school_id'], ['id'])
    op.drop_column('student', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_ibfk_1', 'student', 'user', ['user_id'], ['id'])
    op.drop_column('student', 'school_id')
    op.drop_table('school')
    # ### end Alembic commands ###
