"""add column updated and created_at to table Student

Revision ID: c286792a4256
Revises: 602010d747d3
Create Date: 2019-01-28 06:39:35.561641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c286792a4256'
down_revision = '602010d747d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('student', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'created_at')
    # ### end Alembic commands ###
