"""remove column name on table parent

Revision ID: c53abdcc053d
Revises: 3fb9af5490a0
Create Date: 2019-01-27 16:09:41.347124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c53abdcc053d'
down_revision = '3fb9af5490a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
