"""add column foreign key for user and student

Revision ID: dd4adf2842e8
Revises: de233741c708
Create Date: 2019-01-25 17:21:57.514215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4adf2842e8'
down_revision = 'de233741c708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###
