"""change column name on table User, username to name

Revision ID: f1080da71171
Revises: 439891eb1f64
Create Date: 2019-01-24 16:46:49.777898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1080da71171'
down_revision = '439891eb1f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
